import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const downloadLabReportPDF = (test) => {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("MediTrack", 14, 18);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Laboratory Report", 14, 30);

  const reportId = `LAB-${String(test.id || "001").padStart(3, "0")}`;
  doc.text(reportId, pageWidth - 14, 30, { align: "right" });

  doc.setTextColor(30, 30, 30);

  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Test Details", 14, 56);

  autoTable(doc, {
    startY: 62,
    head: [["Field", "Details"]],
    body: [
      ["Report ID", reportId],
      ["Patient Name", test.patientName || "N/A"],
      ["Test Name", test.testName || "N/A"],
      ["Amount", `Rs. ${test.amount || 0}`],
      [
        "Status",
        test.status || "Pending",
      ],
      [
        "Date",
        test.date
          ? new Date(test.date).toLocaleDateString("en-IN", {
              day: "2-digit",
              month: "long",
              year: "numeric",
            })
          : "N/A",
      ],
    ],
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: 255,
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    styles: {
      fontSize: 11,
      cellPadding: 5,
    },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 60 },
    },
  });

  const finalY = doc.lastAutoTable.finalY + 14;

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(
    "This report is generated by MediTrack Hospital Management System.",
    14,
    finalY
  );
  doc.text(
    `Generated on: ${new Date().toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "long",
      year: "numeric",
    })}`,
    14,
    finalY + 7
  );

  doc.save(`Lab_Report_${reportId}.pdf`);
};